### PR TITLE
ReadMe: Grammer-Correct :)

### PR DESCRIPTION
**Pull request by hpnightowl**
*minor

### CODE REVIEW

**Comment by Akianonymus** [comment]
pru

**Comment by Akianonymus** [comment]
check for more mistakes and force push plox

**Comment by hpnightowl** [comment]
lol

**Comment by hpnightowl** [comment]
@Akianonymus sorry done two pull request using mobile phone :) can u contact me in tg-@hpnightowl

**Comment by Akianonymus** [comment]
will pick later

**Comment by hpnightowl** [comment]
ok

**Pull request closed without merging**
